In [4]:
import numpy as np

from sklearn.model_selection import StratifiedGroupKFold

from load_data import load_data

#data load
x_ADHD, y_ADHD, s_ADHD = load_data("/home/unixuser/cdproject/public_data/ADHD", 1)
x_HC, y_HC, s_HC = load_data("/home/unixuser/cdproject/public_data/HC", 0)

#data size 맞춤(numpy 배열화하기 위해)
x_ADHD = [np.resize(eeg, (15000, 19)) for eeg in x_ADHD]
x_HC = [np.resize(eeg, (15000, 19)) for eeg in x_HC]

#x = time x chnnel의 eeg signal(2d ndarray)를 요소로 갖는 List
#y = x의 label List
#s = x의 subject 이름 List
x: np.ndarray = np.array(x_ADHD + x_HC) 
y: np.ndarray = np.array(y_ADHD + y_HC)  
s: np.ndarray = np.array(s_ADHD + s_HC)

sgkf = StratifiedGroupKFold(n_splits=10)
i = 1
for (train_index, test_index) in sgkf.split(x, y, s):
    x_train = x[train_index]
    y_train = y[train_index]
    s_train = s[train_index]

    x_test = x[test_index]
    y_test = y[test_index]
    s_test = s[test_index]

    if (i == 1 or i == 2):
        print(f"fold {i}")
        print(x_train)
        print(y_train)
        print(s_train)
        print(x_test)
        print(y_test)
        print(s_test)
        print("\n")
    i += 1

fold 1
[[[  85.  -19.  163. ...   85.  121.  332.]
  [ 121.  -55.  273. ...  121.  156.  367.]
  [ 191.   85.  347. ...  191.  297.  473.]
  ...
  [ 578.  473.  457. ...  402.  578.  437.]
  [ 473.  226.  457. ...  367.  543.  508.]
  [ 367.  226.  457. ...  261.  578.  367.]]

 [[ -55.  156.  236. ...  -55.  -19. -301.]
  [ -19.  156.  126. ...   85.  156.   15.]
  [  50.  191.  236. ...   50.  191.   85.]
  ...
  [ 156.   50.  200. ...  226.  226.  156.]
  [ 156.   85.  200. ...  226.  226.  191.]
  [ 156.  121.  200. ...  226.  156.  191.]]

 [[ 226.  226.  236. ...  402.  297.  332.]
  [ 191.  156.  273. ...  332.  191.  121.]
  [ 261.  191.  310. ...  297.  156.  121.]
  ...
  [-125. -160. -131. ...  -90.  -55.  191.]
  [-231. -231. -204. ... -160.  -90.   85.]
  [-160. -266. -131. ... -195.  -55.   50.]]

 ...

 [[  50. -231.   16. ...  -55. -195.   85.]
  [ 332.  156.  457. ...  226.  367.  332.]
  [ 332.  156.  457. ...  226.  367.  332.]
  ...
  [ 367.  226.  494. ...  332.  4